### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by semicarbazid** [wojdyr/xylib#17]
Hi,

when I try to compile XYLIB on Linux with mingw64, I get:

../../xylib/pdcif.cpp:535:74: error: call of overloaded ‘S(long long int)’ is ambiguous
                   "Parse error at character " + S(info.stop - vec.begin()));
                                                                          ^
Any idea?

Thanks!

**Comment by wojdyr** [comment]
Hi @semicarbazid 
I cannot test it right now but I made a blind fix through github's web interface.
If you use the latest revision from git it may work now.
Thanks for reporting the problem.

**Comment by semicarbazid** [comment]
Thanks, it worked!
