### ISSUE TITLE
Canberra CNF file n_channels max should be 32768, not 16384

### ISSUE THREAD

**Issue by chris-stallard1** [wojdyr/xylib#20]
xylib/canberra_cnf.cpp, line 227:

    if (n_channels < 256 || n_channels > 16384)
            throw FormatError("Unexpected number of channels" + S(n_channels));

See [2020-08-03-Bsrm1224-5-1-318.08mg-gp1.zip](https://github.com/wojdyr/xylib/files/5037624/2020-08-03-Bsrm1224-5-1-318.08mg-gp1.zip) for an example of a CNF file with 32768 channels.

**Comment by wojdyr** [comment]
I don't remember if there was a reason for putting 16384 there.
Would this CNF file be read correctly if `|| n_channels > 16384` was removed?

**Comment by chris-stallard1** [comment]
Sorry to come back to this after so long, but the file is read correctly if `|| n_channels > 16384` is removed.
