### ISSUE TITLE
sample urls

### ISSUE THREAD

**Issue by Yohko** [wojdyr/xylib#6]
Hi Marcin,

you may change the link in the "sample-urls" for the Spectra Omicron XPS data example.
The repository does not exist any more.
Instead use https://github.com/Yohko/importtool/blob/master/samples/Spectra.1
or just add the file directly to xylib.
There is also an issue with Specslab2xy import. It does not load the file with data in the “Snapshot (FAT)” (https://github.com/Yohko/importtool/blob/master/samples/SpecsLab2xyonly_SFAT.xy). Normally you just need to add this scan mode.

best,
Matthias

**Comment by wojdyr** [comment]
SpecsLab2xyonly_SFAT.xy is loaded now - hopefully correctly
