### ISSUE TITLE
Wrong x-axis for import of SPECS .xy files when using binding energy

### ISSUE THREAD

**Issue by Ponder-Stibbons** [wojdyr/xylib#7]
Hi Marcin,

as you suggested in the Debian Bug #787623, I am filing this bug against xylib:

When opening a SPECS .xy file, the energy (x-) axis gets reversed:

If the input file is in binding energy, the x-axis is not taken as-is, but the photon energy is subtracted, which reverses the axis. It does work properly, if the input file has the x-axis as kinetic energy. So probably, the parameter "Kinetic Energy Axis: yes/no" in the header is ignored.

If "Kinetic Energy Axis: yes" == True, the photon energy (parameter "Excitation Energy:") should be subtracted, if "Kinetic Energy Axis: yes" == False, the axis should be taken as is.

This would, however, result in positive binding energies, whereas the implemented method for the case of "kinetic energy:  yes" results in negative binding energies. Whether binding energies should be positive or negative is kind of a matter of taste in the community, but for the sake of consistency, I would suggest to revert the sign for the implemented routine in the case of "kin. en. : yes".

Best,

Matthias

**Comment by wojdyr** [comment]
Sorry for late reply. When you reported the debian bug I forwarded it to @Yohko and he replied with a patch that removes subtracting excitation energy at all in the FixedAnalyzerTransmission scan mode. I've just applied that change.
@Yohko: what do you think about subtracting photon energy if "Kinetic Energy Axis: yes" and reverting the sign?

**Comment by Ponder-Stibbons** [comment]
Hi Marcin,

ah, I think removing the operation of subtracting the photon energy is
not really intended. See also the commit of Matthias (the R one) to his
Igor routine:
https://github.com/Yohko/importtool/commit/99cfdda2901808c30a6fee1d184b9dcfd2d29db7

So for most applications, you want to work with the binding energy. But
the SPECS .xy file comes with the option to store the x-axis either in
binding energy or in kinetic energy, which is stated in the header
"Kinetic Energy Axis:" "yes/no". If you have the kinetic energy in your
.xy file, you need to subtract the photon energy to convert to binding
energy (and revert the sign, if you want positive energies). If the
trigger in the header is "no", then one just takes the x-axis as is
(positive binding energies).

Regarding the sign of the binding energy: That depends on your
perspective, if you're sitting (or rather flying, as this is E_Vac in
infinity :D) in the vacuum or sitting on your atom. Physicists often
have the former perspective, chemists the latter. Regarding the use in
the literature, I would say that most people are rather sitting on their
little atoms, i.e. use positive binding energies.

Best,

Matthias (the M one)

**Comment by wojdyr** [comment]
Thanks a lot for explanation. I'd have a look at this file format and maybe rewrite the implementation in xylib. I have two examples of this file format: https://github.com/wojdyr/xylib/blob/master/samples/specsxy_example.xy from MR and the one from debian bug report. Do you have by chance example with scan mode FixedEnergies? From the source code it seems to be handled differently. I'm afraid of making major changes while not being able to test them.

**Comment by wojdyr** [comment]
Current implementation is quite complicated and not complete. I'm thinking about replacing it with a new one that would just read data as it was exported, treating empty line as block separators and taking column labels from `# ColumnLabels:` lines.
If switching between KE and BE is useful, it could be handled by Fityk GUI.

**Comment by martukas** [comment]
I think this email may have been misaddressed to me

**Comment by wojdyr** [comment]
I've completely rewritten reading of this file format, closing this issue. Let me know if you find other problems in the future.
